projects:
  default:
    schema: "node_modules/@shopify/hydrogen/dist/storefront.schema.json"
    documents:
      - "!*.d.ts"
      - "*.{ts,tsx,js,jsx}"
      - "app/**/*.{ts,tsx,js,jsx}"
      - "!app/graphql/**/*.{ts,tsx,js,jsx}"
  customer-account:
    schema: "node_modules/@shopify/hydrogen/dist/customer-account.schema.json"
    documents:
      - "app/graphql/customer-account/**/*.{ts,tsx,js,jsx}"
